CREATE TABLE USER_INFO(
ID VARCHAR2(20) PRIMARY KEY,    --아이디 기본키
PW VARCHAR2(20) NOT NULL,       --비밀번호
NAME VARCHAR2(15) NOT NULL,     --이름
GENDER CHAR(1) DEFAULT 'M' CHECK(GENDER IN('M','W')),   --성별 기본값M
EMAIL VARCHAR2(30)              --이메일
);

CREATE SEQUENCE POST_NO NOCACHE;

CREATE TABLE POST(
NO NUMBER PRIMARY KEY,          --글번호 기본키, 시퀀스
ID VARCHAR2(20) NOT NULL,       --아이디 외래키 참조
TITLE VARCHAR2(100),             --제목
POST_CONTENT VARCHAR2(300),     --내용
LOGTIME DATE,                   --작성 날짜
FOREIGN KEY(ID) REFERENCES USER_INFO(ID)
);